### ISSUE TITLE
[Webページ] 色名の重複

### ISSUE THREAD

**Issue by cmplstofB** [akinomyoga/contra#1]
制御シーケンスについてのWebページ[第2644行](https://github.com/akinomyoga/contra/blob/e47807cc7a6a5b4facb9b1c245b8ad85ab1aa4a1/escseq.html#L2644)と[第2648行](https://github.com/akinomyoga/contra/blob/e47807cc7a6a5b4facb9b1c245b8ad85ab1aa4a1/escseq.html#L2648)（ソースコード）において，green及びcyanに同じ「碧色」という語が訳し当てられています。例えばgreenの訳語を「緑色」にするなど，両者を区別できるようにしたほうがいいと思います。

**Comment by akinomyoga** [comment]
ありがとうございます! 本当ですね。下の高輝度の方が草色になっているのでこれは緑色にするつもりだったのでしょう。直しておきます

**Comment by akinomyoga** [comment]
cb12582 直しました
